import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// 複製短語映射檔到輸出目錄（按需載入，不打包進 main.js）
function copyPhraseFiles() {
  const files = ["st_phrases.json", "ts_phrases.json"];
  for (const f of files) {
    const src = `src/data/${f}`;
    const dest = f;
    if (fs.existsSync(src)) {
      fs.copyFileSync(src, dest);
      console.log(`  copied ${src} → ${dest} (${(fs.statSync(src).size / 1024).toFixed(0)} KB)`);
    }
  }
}

if (prod) {
  const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: ["obsidian", "electron", ...builtins],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: false,
    treeShaking: true,
    outfile: "main.js",
    minify: true,
  });
  await context.rebuild();
  context.dispose();
  copyPhraseFiles();
  process.exit(0);
} else {
  const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: ["obsidian", "electron", ...builtins],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: "inline",
    treeShaking: true,
    outfile: "main.js",
    minify: false,
  });
  await context.watch();
  // 開發模式也複製一次
  copyPhraseFiles();
}
